spring.http.converters.preferred-json-mapper=gson

kafka.bootstrap.server=192.168.0.37:9091
flink.rest.server=192.168.0.37:8081

plug.path=/usr/local/lib/i8/plug
node.path=/usr/local/lib/i8/node
root.path=/usr/local/lib/i8